// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pb struct {
	GamerLoginC2S        *Pb_GamerLoginC2S      `protobuf:"bytes,1,opt,name=gamerLoginC2S" json:"gamerLoginC2S,omitempty"`
	GamerLoginS2C        *Pb_GamerLoginS2C      `protobuf:"bytes,2,opt,name=gamerLoginS2C" json:"gamerLoginS2C,omitempty"`
	GamerGlobalChatC2S   *Pb_GamerGlobalChatC2S `protobuf:"bytes,3,opt,name=gamerGlobalChatC2S" json:"gamerGlobalChatC2S,omitempty"`
	GamerGlobalChatS2C   *Pb_GamerGlobalChatS2C `protobuf:"bytes,4,opt,name=gamerGlobalChatS2C" json:"gamerGlobalChatS2C,omitempty"`
	GamerChatC2S         *Pb_GamerChatC2S       `protobuf:"bytes,5,opt,name=gamerChatC2S" json:"gamerChatC2S,omitempty"`
	GamerChatS2C         *Pb_GamerChatS2C       `protobuf:"bytes,6,opt,name=gamerChatS2C" json:"gamerChatS2C,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Pb) Reset()         { *m = Pb{} }
func (m *Pb) String() string { return proto.CompactTextString(m) }
func (*Pb) ProtoMessage()    {}
func (*Pb) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_0967f4a727e9b91a, []int{0}
}
func (m *Pb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pb.Unmarshal(m, b)
}
func (m *Pb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pb.Marshal(b, m, deterministic)
}
func (dst *Pb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pb.Merge(dst, src)
}
func (m *Pb) XXX_Size() int {
	return xxx_messageInfo_Pb.Size(m)
}
func (m *Pb) XXX_DiscardUnknown() {
	xxx_messageInfo_Pb.DiscardUnknown(m)
}

var xxx_messageInfo_Pb proto.InternalMessageInfo

func (m *Pb) GetGamerLoginC2S() *Pb_GamerLoginC2S {
	if m != nil {
		return m.GamerLoginC2S
	}
	return nil
}

func (m *Pb) GetGamerLoginS2C() *Pb_GamerLoginS2C {
	if m != nil {
		return m.GamerLoginS2C
	}
	return nil
}

func (m *Pb) GetGamerGlobalChatC2S() *Pb_GamerGlobalChatC2S {
	if m != nil {
		return m.GamerGlobalChatC2S
	}
	return nil
}

func (m *Pb) GetGamerGlobalChatS2C() *Pb_GamerGlobalChatS2C {
	if m != nil {
		return m.GamerGlobalChatS2C
	}
	return nil
}

func (m *Pb) GetGamerChatC2S() *Pb_GamerChatC2S {
	if m != nil {
		return m.GamerChatC2S
	}
	return nil
}

func (m *Pb) GetGamerChatS2C() *Pb_GamerChatS2C {
	if m != nil {
		return m.GamerChatS2C
	}
	return nil
}

type Pb_GamerLoginC2S struct {
	Id                   *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pb_GamerLoginC2S) Reset()         { *m = Pb_GamerLoginC2S{} }
func (m *Pb_GamerLoginC2S) String() string { return proto.CompactTextString(m) }
func (*Pb_GamerLoginC2S) ProtoMessage()    {}
func (*Pb_GamerLoginC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_0967f4a727e9b91a, []int{0, 0}
}
func (m *Pb_GamerLoginC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pb_GamerLoginC2S.Unmarshal(m, b)
}
func (m *Pb_GamerLoginC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pb_GamerLoginC2S.Marshal(b, m, deterministic)
}
func (dst *Pb_GamerLoginC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pb_GamerLoginC2S.Merge(dst, src)
}
func (m *Pb_GamerLoginC2S) XXX_Size() int {
	return xxx_messageInfo_Pb_GamerLoginC2S.Size(m)
}
func (m *Pb_GamerLoginC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Pb_GamerLoginC2S.DiscardUnknown(m)
}

var xxx_messageInfo_Pb_GamerLoginC2S proto.InternalMessageInfo

func (m *Pb_GamerLoginC2S) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type Pb_GamerLoginS2C struct {
	Json                 *string  `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pb_GamerLoginS2C) Reset()         { *m = Pb_GamerLoginS2C{} }
func (m *Pb_GamerLoginS2C) String() string { return proto.CompactTextString(m) }
func (*Pb_GamerLoginS2C) ProtoMessage()    {}
func (*Pb_GamerLoginS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_0967f4a727e9b91a, []int{0, 1}
}
func (m *Pb_GamerLoginS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pb_GamerLoginS2C.Unmarshal(m, b)
}
func (m *Pb_GamerLoginS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pb_GamerLoginS2C.Marshal(b, m, deterministic)
}
func (dst *Pb_GamerLoginS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pb_GamerLoginS2C.Merge(dst, src)
}
func (m *Pb_GamerLoginS2C) XXX_Size() int {
	return xxx_messageInfo_Pb_GamerLoginS2C.Size(m)
}
func (m *Pb_GamerLoginS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Pb_GamerLoginS2C.DiscardUnknown(m)
}

var xxx_messageInfo_Pb_GamerLoginS2C proto.InternalMessageInfo

func (m *Pb_GamerLoginS2C) GetJson() string {
	if m != nil && m.Json != nil {
		return *m.Json
	}
	return ""
}

type Pb_GamerGlobalChatC2S struct {
	Data                 *string  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pb_GamerGlobalChatC2S) Reset()         { *m = Pb_GamerGlobalChatC2S{} }
func (m *Pb_GamerGlobalChatC2S) String() string { return proto.CompactTextString(m) }
func (*Pb_GamerGlobalChatC2S) ProtoMessage()    {}
func (*Pb_GamerGlobalChatC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_0967f4a727e9b91a, []int{0, 2}
}
func (m *Pb_GamerGlobalChatC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pb_GamerGlobalChatC2S.Unmarshal(m, b)
}
func (m *Pb_GamerGlobalChatC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pb_GamerGlobalChatC2S.Marshal(b, m, deterministic)
}
func (dst *Pb_GamerGlobalChatC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pb_GamerGlobalChatC2S.Merge(dst, src)
}
func (m *Pb_GamerGlobalChatC2S) XXX_Size() int {
	return xxx_messageInfo_Pb_GamerGlobalChatC2S.Size(m)
}
func (m *Pb_GamerGlobalChatC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Pb_GamerGlobalChatC2S.DiscardUnknown(m)
}

var xxx_messageInfo_Pb_GamerGlobalChatC2S proto.InternalMessageInfo

func (m *Pb_GamerGlobalChatC2S) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

type Pb_GamerGlobalChatS2C struct {
	Data                 *string  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pb_GamerGlobalChatS2C) Reset()         { *m = Pb_GamerGlobalChatS2C{} }
func (m *Pb_GamerGlobalChatS2C) String() string { return proto.CompactTextString(m) }
func (*Pb_GamerGlobalChatS2C) ProtoMessage()    {}
func (*Pb_GamerGlobalChatS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_0967f4a727e9b91a, []int{0, 3}
}
func (m *Pb_GamerGlobalChatS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pb_GamerGlobalChatS2C.Unmarshal(m, b)
}
func (m *Pb_GamerGlobalChatS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pb_GamerGlobalChatS2C.Marshal(b, m, deterministic)
}
func (dst *Pb_GamerGlobalChatS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pb_GamerGlobalChatS2C.Merge(dst, src)
}
func (m *Pb_GamerGlobalChatS2C) XXX_Size() int {
	return xxx_messageInfo_Pb_GamerGlobalChatS2C.Size(m)
}
func (m *Pb_GamerGlobalChatS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Pb_GamerGlobalChatS2C.DiscardUnknown(m)
}

var xxx_messageInfo_Pb_GamerGlobalChatS2C proto.InternalMessageInfo

func (m *Pb_GamerGlobalChatS2C) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

type Pb_GamerChatC2S struct {
	Data                 *string  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Id                   *string  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pb_GamerChatC2S) Reset()         { *m = Pb_GamerChatC2S{} }
func (m *Pb_GamerChatC2S) String() string { return proto.CompactTextString(m) }
func (*Pb_GamerChatC2S) ProtoMessage()    {}
func (*Pb_GamerChatC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_0967f4a727e9b91a, []int{0, 4}
}
func (m *Pb_GamerChatC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pb_GamerChatC2S.Unmarshal(m, b)
}
func (m *Pb_GamerChatC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pb_GamerChatC2S.Marshal(b, m, deterministic)
}
func (dst *Pb_GamerChatC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pb_GamerChatC2S.Merge(dst, src)
}
func (m *Pb_GamerChatC2S) XXX_Size() int {
	return xxx_messageInfo_Pb_GamerChatC2S.Size(m)
}
func (m *Pb_GamerChatC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Pb_GamerChatC2S.DiscardUnknown(m)
}

var xxx_messageInfo_Pb_GamerChatC2S proto.InternalMessageInfo

func (m *Pb_GamerChatC2S) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *Pb_GamerChatC2S) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type Pb_GamerChatS2C struct {
	Data                 *string  `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	FromId               *string  `protobuf:"bytes,2,opt,name=fromId" json:"fromId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pb_GamerChatS2C) Reset()         { *m = Pb_GamerChatS2C{} }
func (m *Pb_GamerChatS2C) String() string { return proto.CompactTextString(m) }
func (*Pb_GamerChatS2C) ProtoMessage()    {}
func (*Pb_GamerChatS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_0967f4a727e9b91a, []int{0, 5}
}
func (m *Pb_GamerChatS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pb_GamerChatS2C.Unmarshal(m, b)
}
func (m *Pb_GamerChatS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pb_GamerChatS2C.Marshal(b, m, deterministic)
}
func (dst *Pb_GamerChatS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pb_GamerChatS2C.Merge(dst, src)
}
func (m *Pb_GamerChatS2C) XXX_Size() int {
	return xxx_messageInfo_Pb_GamerChatS2C.Size(m)
}
func (m *Pb_GamerChatS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Pb_GamerChatS2C.DiscardUnknown(m)
}

var xxx_messageInfo_Pb_GamerChatS2C proto.InternalMessageInfo

func (m *Pb_GamerChatS2C) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *Pb_GamerChatS2C) GetFromId() string {
	if m != nil && m.FromId != nil {
		return *m.FromId
	}
	return ""
}

func init() {
	proto.RegisterType((*Pb)(nil), "pb")
	proto.RegisterType((*Pb_GamerLoginC2S)(nil), "pb.GamerLoginC2S")
	proto.RegisterType((*Pb_GamerLoginS2C)(nil), "pb.GamerLoginS2C")
	proto.RegisterType((*Pb_GamerGlobalChatC2S)(nil), "pb.GamerGlobalChatC2S")
	proto.RegisterType((*Pb_GamerGlobalChatS2C)(nil), "pb.GamerGlobalChatS2C")
	proto.RegisterType((*Pb_GamerChatC2S)(nil), "pb.GamerChatC2S")
	proto.RegisterType((*Pb_GamerChatS2C)(nil), "pb.GamerChatS2C")
}

func init() { proto.RegisterFile("Message.proto", fileDescriptor_Message_0967f4a727e9b91a) }

var fileDescriptor_Message_0967f4a727e9b91a = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x59, 0xac, 0x03, 0x9f, 0xab, 0xe8, 0x3b, 0x8c, 0xd1, 0x8b, 0xa2, 0x97, 0x9d, 0x7a,
	0x08, 0x82, 0xe0, 0xb5, 0xe0, 0x10, 0xf4, 0x92, 0x7e, 0x82, 0x94, 0xd6, 0x5a, 0xd9, 0x96, 0xd2,
	0xf6, 0xe3, 0x7b, 0x18, 0x2f, 0x24, 0x25, 0x8f, 0x65, 0xb7, 0x34, 0xf9, 0xfd, 0xfe, 0xef, 0xdf,
	0x07, 0xe9, 0x77, 0x33, 0x8e, 0xba, 0x6d, 0xf2, 0x7e, 0x30, 0x93, 0x79, 0xfe, 0x4f, 0x40, 0xf4,
	0x15, 0xbe, 0x41, 0xda, 0xea, 0x43, 0x33, 0x7c, 0x99, 0xb6, 0x3b, 0x16, 0xb2, 0xdc, 0x2c, 0x9e,
	0x16, 0xdb, 0x5b, 0xf9, 0x90, 0xf7, 0x55, 0xbe, 0x0b, 0x1f, 0x14, 0xe7, 0xb8, 0x58, 0xca, 0x62,
	0x23, 0x62, 0x62, 0x29, 0x0b, 0xc5, 0x39, 0xfc, 0x00, 0xb4, 0x17, 0xbb, 0xbd, 0xa9, 0xf4, 0xbe,
	0xf8, 0xd5, 0x13, 0x8d, 0xbd, 0xb2, 0xf6, 0x7a, 0xb6, 0xd9, 0xab, 0x8a, 0x18, 0x91, 0x1c, 0x6a,
	0x91, 0x5c, 0xcc, 0xa1, 0x2a, 0x11, 0x03, 0x5f, 0x61, 0x65, 0x6f, 0x7d, 0x93, 0x6b, 0x9b, 0x70,
	0x3f, 0x27, 0xf8, 0x0e, 0x8c, 0x62, 0x16, 0xcd, 0x5d, 0x46, 0x2c, 0x9a, 0xc8, 0xa8, 0xec, 0x11,
	0x52, 0xb6, 0x54, 0xbc, 0x03, 0xd1, 0xd5, 0x76, 0xe7, 0x37, 0x4a, 0x74, 0x75, 0xf6, 0x12, 0x02,
	0xd4, 0x0e, 0x21, 0xf9, 0x1b, 0xcd, 0xd1, 0x21, 0xf6, 0x9c, 0x6d, 0x01, 0xcf, 0x77, 0x44, 0x64,
	0xad, 0x27, 0xed, 0x49, 0x3a, 0x47, 0x48, 0x97, 0x79, 0x46, 0x4a, 0x58, 0x85, 0x7f, 0x1b, 0x63,
	0x5c, 0x59, 0x31, 0x97, 0x7d, 0x0f, 0x9c, 0x0b, 0xb9, 0xb8, 0x86, 0xe5, 0xcf, 0x60, 0x0e, 0x9f,
	0xde, 0x73, 0x5f, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0xb8, 0xed, 0xc8, 0x8e, 0x02, 0x00,
	0x00,
}
